packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@scarf/scarf': true
  esbuild: true
  protobufjs: true
  prisma: true
  '@prisma/engines': true
