-- AlterTable
ALTER TABLE "projects" ADD COLUMN     "app_platform_owner" TEXT,
ADD COLUMN     "arch_impact" TEXT,
ADD COLUMN     "business_pm" TEXT,
ADD COLUMN     "business_sponsor" TEXT,
ADD COLUMN     "deps_assumptions_risk" TEXT,
ADD COLUMN     "ea_alignment_conducted" BOOLEAN,
ADD COLUMN     "ea_comment" TEXT,
ADD COLUMN     "ea_involved" BOOLEAN,
ADD COLUMN     "gxp_relevant" BOOLEAN,
ADD COLUMN     "ic_recharge_capex_cents" INTEGER,
ADD COLUMN     "ic_recharge_opex_cents" INTEGER,
ADD COLUMN     "it_security_alignment_conducted" BOOLEAN,
ADD COLUMN     "it_security_comment" TEXT,
ADD COLUMN     "it_security_involved" BOOLEAN,
ADD COLUMN     "license_cost_cents" INTEGER,
ADD COLUMN     "license_expected_users" INTEGER,
ADD COLUMN     "license_in_budget" BOOLEAN,
ADD COLUMN     "license_metric" TEXT,
ADD COLUMN     "licenses_needed" BOOLEAN,
ADD COLUMN     "maintenance_l1" TEXT,
ADD COLUMN     "maintenance_l2" TEXT,
ADD COLUMN     "maintenance_l3" TEXT,
ADD COLUMN     "necessity" TEXT,
ADD COLUMN     "objective" TEXT,
ADD COLUMN     "scope" TEXT;
